#!/bin/bash

success () {
    echo "$(tput setaf 2)$1$(tput sgr0)"
}

warning () {
    echo "$(tput setaf 1)$1$(tput sgr0)"
}

IS_RASPBIAN=`cat /etc/*-release | grep Raspbian`

if [[ "" == $IS_RASPBIAN ]]; then
    warning "Warning!"
    echo "Please only run this script on Raspbian on your Raspberry Pi"
    exit 1;
fi

FORCE=$1

confirm () {
    if [ "$FORCE" == '-y' ]; then
        true
    else
        read -r -p "$1 [y/N] " response < /dev/tty
        response=${response,,}
        if [[ $response =~ ^(yes|y)$ ]]; then
                true
        else
                false
        fi
    fi
}

echo ""
echo "This script will let you configure your Pi audio output!"
echo ""
warning "--- Warning ---"
echo ""
echo "Always be careful when running scripts and commands"
echo "copied from the internet. Ensure they are from a"
echo "trusted source."
echo ""
echo "If you want to see what this script does before"
echo "running it, you should run:"
echo "    \curl -sS get.pimoroni.com/audio"
echo ""
echo ""

if confirm "Do you wish to continue?"; then
    echo ""
    echo "Please choose an audio output mode:"
    echo "0 : Automatic"
    echo "1 : Output to analogue (headphone/speaker jack)"
    echo "2 : Output to digital (HDMI port)"
    echo ""
    read -r -p "Enter an option [0-2]:" choice < /dev/tty

    if ! [[ $choice =~ '^[0-2]$' ]]; then

        echo ""
        amixer cset numid=3 $choice  > /dev/tty
        echo ""
        success "Output mode changed!"
    else
        warning "Invalid option..."

    fi    echo ""
else
    echo ""
    echo "Aborting..."
    echo ""
fi
