#!/bin/bash

# This boilerplate get script does nothing
# but serves as an example for making your own.
# Run with -y switch to skip confirmation and intro.

# Core functions/helpers

confirm () {
	read -r -p "$1 [y/N] " response < /dev/tty
	response=${response,,}
	if [[ $response =~ ^(yes|y)$ ]]; then
		true
	else
		false
	fi
}

pip_pkg_req () {
	PIP_CHK=$(pip search $1 | grep INSTALLED)
	if [ "" == "$PIP_CHK" ]; then
		true	
	else
		false
	fi
}

apt_pkg_req () {
	APT_CHK=$(dpkg-query -W --showformat='${Status}\n' $1|grep "install ok installed")
	if [ "" == "$APT_CHK" ]; then
		true
	else
		false
	fi
}

success () {
	echo "$(tput setaf 2)$1$(tput sgr0)"
}

warning () {
	echo "$(tput setaf 1)$1$(tput sgr0)"
}

if ! [[ $1 == '-y' ]]; then

	echo ""
	echo "This script will let you configure your Pi audio output!"
	echo ""
	warning "--- Warning ---"
	echo ""
	echo "Always be careful when running scripts and commands"
	echo "copied from the internet. Ensure they are from a"
	echo "trusted source."
	echo ""
	echo "If you want to see what this script does before"
	echo "running it, you should run:"
	echo "    \curl -sS get.pimoroni.com/boilerplate"
	echo ""
	echo ""

	if confirm "Do you wish to continue?"; then
		RESP="true"
	else
		RESP="false"
	fi

fi

if [[ $RESP == "true" ]] || [[ $1 == '-y' ]]; then

	echo ""
	echo "Please choose an audio output mode:"
	echo "0 : Automatic"
	echo "1 : Output to analogue (headphone/speaker jack)"
	echo "2 : Output to digital (HDMI port)"
	echo ""
	read -r -p "Enter an option [0-2]:" choice < /dev/tty

	if ! [[ $choice =~ '^[0-2]$' ]]; then

		echo ""
		amixer cset numid=3 $choice  > /dev/tty
		echo ""
		success "Output mode changed!"

	else

		warning "Invalid option..."

	fi
	echo ""
fi
