#!/bin/bash

echo ""
echo "This script will enable i2c and spi on your Raspberry Pi"
echo ""
echo "--- Warning ---"
echo ""
echo "Always be careful when running scripts and commands"
echo "copied from the internet. Ensure they are from a"
echo "trusted source."
echo ""
echo "If you want to see what this script does before"
echo "running it, you should run:"
echo "    \curl -sS get.pimoroni.com/unicornhat"
echo ""
echo ""

read -r -p "Do you wish to continue? [y/n]" response < /dev/tty
response=${response,,}

if [[ $response =~ ^(yes|y)$ ]]
then

	\curl -sS get.pimoroni.com/i2c | bash -s - "-y"
	\curl -sS get.pimoroni.com/spi | bash -s - "-y"

fi

echo ""
echo "All done!"
echo ""
