#!/bin/bash

PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $1|grep "install ok installed")
echo ""
echo "Checking for $1..."
if [ "" == "$PKG_OK" ]; then
	echo "$1 required. Installing."
	echo "Running sudo apt-get install $1"
	echo ""
	sudo apt-get --force-yes --yes install $1
	echo ""
else
	echo "$1 already installed."
fi
echo ""
