#!/bin/bash

confirm () {
	read -r -p "$1 [y/N] " response < /dev/tty
	response=${response,,}
	if [[ $response =~ ^(yes|y)$ ]]; then
		true
	else
		false
	fi
}

pip_pkg_req () {
	PIP_CHK=$(pip search $1 | grep INSTALLED)
	if [ "" == "$PIP_CHK" ]; then
		true	
	else
		false
	fi
}

apt_pkg_req () {
	APT_CHK=$(dpkg-query -W --showformat='${Status}\n' $1|grep "install ok installed")
	if [ "" == "$APT_CHK" ]; then
		true
	else
		false
	fi
}

success () {
	echo "$(tput setaf 2)$1$(tput sgr0)"
}

warning () {
	echo "$(tput setaf 1)$1$(tput sgr0)"
}

IS_RASPBIAN=`cat /etc/*-release | grep Raspbian`

if [[ "" == $IS_RASPBIAN ]]; then
	warning "Warning!"
	echo "Please only run this script on Raspbian on your Raspberry Pi"
	exit 1;
fi

if ! [[ $1 == '-y' ]]
then

	echo ""
	echo "This script will install pibrella and dependencies"
	echo ""
	warning "--- Warning ---"
	echo ""
	echo "Always be careful when running scripts and commands"
	echo "copied from the internet. Ensure they are from a"
	echo "trusted source."
	echo ""
	echo "If you want to see what this script does before"
	echo "running it, you should run:"
	echo "    \curl -sS get.pimoroni.com/pibrella"
	echo ""
	echo ""

	if confirm "Do you wish to continue?"; then
		RESP="true"
	else
		RESP="false"
	fi
fi

if [[ $RESP == "true" ]] || [[ $1 == '-y' ]]; then

	echo ""
	if confirm "Pibrella requires I2C, enable now?"; then

		\curl -sS get.pimoroni.com/spi | bash -s - "-y"

	fi

	echo ""
	echo "Checking for install requirements..."

	if apt_pkg_req "python-pip" || apt_pkg_req "python-dev"; then

		echo ""
		echo "One or more requires packages not found..."
		echo ""
		echo "Updating package indexes..."
		echo ""
		sudo apt-get update

		echo ""
		echo "Installing required packages..."
		echo ""
		sudo apt-get --force-yes --yes install python-dev python-pip
	else
		echo ""
		success "Found!"	
	fi

	echo ""
	echo "Checking for Python modules..."
	
	if pip_pkg_req "pibrella"; then

		echo ""
		echo "Insalling Python module"
		echo ""

		sudo pip install pibrella -I
	
	else
	
		echo ""
		success "Found!"
		echo ""

		if confirm "Python modules found. Reinstall/Update?"; then

			echo ""
			sudo pip install pibrella -I
			echo ""

		fi
	fi

	echo ""

	if confirm "Would you like to install Scratch GPIO5 with Pibrella support?"; then
		echo "Installing..."
		export TMPDIR=`mktemp -d /tmp/selfextract.XXXXXX`
		curl -sSL http://goo.gl/Pthh62 | sed '1,/^__ARCHIVE_BELOW__/d' | tar xzv -C $TMPDIR

		CDIR=`pwd`
		cd $TMPDIR
		sudo ./installer.sh $1
		
		cd $CDIR
		rm -rf $TMPDIR
		
	fi

	echo ""

	if [ -d ${pwd}/pibrella ]; then
		if confirm "Would you like to download Pibrella example code?"; then

			echo ""
			echo "Downloading to $(pwd)/pibrella"
			echo ""
			git clone https://github.com/pimoroni/pibrella
	
		fi
	fi

	echo ""

	sudo python -c $'from pibrella import backlight,lcd\n\nbacklight.rgb(0,255,0)\nlcd.clear()\nlcd.write("Install CompleteHave fun!")' >> /dev/null 2>&1
	echo ""
	success "All done!"
	echo ""
	echo "Enjoy your Pibrella!"
	echo ""

else
	echo ""
	echo "Aborting..."
	echo ""
fi
