#!/bin/bash

success () {
        echo "$(tput setaf 2)$1$(tput sgr0)"
}

warning () {
        echo "$(tput setaf 1)$1$(tput sgr0)"
}

IS_RASPBIAN=`cat /etc/*-release | grep Raspbian`

if [[ "" == $IS_RASPBIAN ]]; then
	warning "Warning!"
	echo "Please only run this script on Raspbian on your Raspberry Pi"
	exit 1;
fi

if ! [[ $1 == '-y' ]]
then
	echo ""
	echo "This script will enable spi on your Raspberry Pi"
	echo ""
	warning "--- Warning ---"
	echo ""
	echo "Always be careful when running scripts and commands"
	echo "copied from the internet. Ensure they are from a"
	echo "trusted source."
	echo ""
	echo "If you want to see what this script does before"
	echo "running it, you should run:"
	echo "    \curl -sS get.pimoroni.com/spi"
	echo ""
	echo ""

	read -r -p "Do you wish to continue? [y/n]" response < /dev/tty
	response=${response,,}
fi

if [[ $response =~ ^(yes|y)$ ]] || [[ $1 == '-y' ]]
then
	if [ -e /etc/modprobe.d/raspi-blacklist.conf ] && grep -q "^blacklist[[:space:]]*spi-bcm2708" /etc/modprobe.d/raspi-blacklist.conf; then
		echo ""
		echo "Enabling SPI..."
		echo ""

		echo "Commenting out Blacklist entry in "
		echo "/etc/modprobe.d/raspi-blacklist.conf"
		sudo sed -i /etc/modprobe.d/raspi-blacklist.conf -e "s/^blacklist[[:space:]]*spi-bcm2708.*/#blacklist spi-bcm2708/"
		sudo modprobe spi-bcm2708

		echo ""
		success "SPI enabled"
	else

		echo ""
		success "SPI Already Enabled"
	fi

	if ! grep -qe "spi-bcm2708" "/etc/modules"; then
		echo ""
		echo "Adding "
		echo "spi-bcm2708" | sudo tee -a "/etc/modules"
		echo " to /etc/modules"
	fi


else
	echo ""
	echo "Aborting..."
	echo ""
fi

