#!/bin/bash

FORCE=$1

if [ $EUID -ne 0 ]; then
        USER_HOME=$(getent passwd $USER | cut -d: -f6)
else
        USER_HOME=$(getent passwd $SUDO_USER | cut -d: -f6)
fi
WORKING_DIR=$USER_HOME/Pimoroni

if [ -e /usr/bin/pip3  ]; then
        PIP3_BIN="pip3"
else
        PIP3_BIN="pip-3.2"
fi

confirm () {
        if [ "$FORCE" == '-y' ]; then
            true
        else
            read -r -p "$1 [y/N] " response < /dev/tty
            response=${response,,}
            if [[ $response =~ ^(yes|y)$ ]]; then
                    true
            else
                    false
            fi
        fi
}

pip_pkg_req3 () {
        PIP_CHK=$($PIP3_BIN search $1 | grep INSTALLED)
        if [ "" == "$PIP_CHK" ]; then
                true
        else
                false
        fi
}

pip_pkg_req () {
        PIP_CHK=$(pip search $1 | grep INSTALLED)
        if [ "" == "$PIP_CHK" ]; then
                true
        else
                false
        fi
}

apt_pkg_req () {
        APT_CHK=$(dpkg-query -W --showformat='${Status}\n' $1|grep "install ok installed")
        if [ "" == "$APT_CHK" ]; then
                true
        else
                false
        fi
}

apt_pkg_install () {
		\curl -sS get.pimoroni.com/package | bash -s - $1 || { warning "Sorry, Apt failed to install $1, I can't continue!" && exit; }
}

success () {
        echo "$(tput setaf 2)$1$(tput sgr0)"
}

warning () {
        echo "$(tput setaf 1)$1$(tput sgr0)"
}

IS_RASPBIAN=`cat /etc/*-release | grep Raspbian`

if [[ "" == $IS_RASPBIAN ]]; then
	warning "Warning!"
	echo "Please only run this script on Raspbian on your Raspberry Pi"
	exit 1;
fi

echo ""
echo "This script will install Unicorn Hat libraries"
echo "and dependencies for both Python 2 and 3."
echo ""
echo "This process may take several minutes."
echo ""
warning "--- Warning ---"
echo ""
echo "Always be careful when running scripts and commands"
echo "copied from the internet. Ensure they are from a"
echo "trusted source."
echo ""
echo "If you want to see what this script does before"
echo "running it, you should run:"
echo "    \curl -sS get.pimoroni.com/unicornhat"
echo ""
echo ""

if confirm "Do you wish to continue?"; then

	echo ""
	echo "Checking install requirements..."
	echo ""

        updatedb=false
        pkgdeplist=( "git" "python-pip" "python-dev" "python3-pip" "python3-dev" )

        for pkgdep in ${pkgdeplist[@]}
            do if apt_pkg_req "$pkgdep" ; then
                   updatedb=true
               fi
            done 

        if $updatedb ; then
		echo "Updating package indexes..."
		sudo apt-get update

		echo ""
		echo "Installing UnicornHat requirements..."

            for pkgdep in ${pkgdeplist[@]}
            do if apt_pkg_req "$pkgdep" ; then
                   apt_pkg_install "$pkgdep"
               fi
            done 
	else
		success "Found!"
	fi

	echo ""
	echo "Checking for Python 2 library..."

	if pip_pkg_req "unicornhat"; then

		echo ""
		echo "Installing UnicornHat for Python 2..."
		if ! sudo pip install unicornhat; then
			warning "Python 2 library install failed!"
			echo ""
			exit
		fi
		success "Done!"
	else
		echo ""
		success "Found!"
		echo ""
		if confirm "Python 2 module found. Reinstall/Update?"; then
			if ! sudo pip install unicornhat -I; then
				warning "Python 2 library install failed!"
				echo ""
				exit
			fi
			success "Done!"
		fi
	fi

	echo ""
	echo "Checking for Python 3 library..."

	if pip_pkg_req3 "unicornhat"; then

		echo ""
		echo "Installing UnicornHat for Python 3..."
		if ! sudo $PIP3_BIN install unicornhat; then
			warning "Python 3 library install failed!"
			echo ""
			exit
		fi
	else

		echo ""
		success "Found!"
		echo ""
		if confirm "Python 3 module found. Reinstall/Update?"; then
			if ! sudo $PIP3_BIN install unicornhat -I; then
				warning "Python 3 library install failed!"
				echo ""
				exit
			fi
		fi
	fi

	echo ""
	echo "Checking for additional modules..."

	if pip_pkg_req "flask"; then
		echo ""
		echo "Unicorn Paint requires the Flask python module ( Python 2.x only )"
		if confirm "Would you like to install it?"; then
			echo ""
			sudo pip install flask
		fi
	else
		echo ""
		success "Found!"
	fi

	echo ""

        if ! [ -d $WORKING_DIR ]; then
                mkdir $WORKING_DIR
        fi

	if ! [ -d $WORKING_DIR/unicornhat ]; then
		echo "Downloading Unicorn Hat examples..."
		export TMPDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
		cd $TMPDIR
		git clone https://github.com/pimoroni/unicornhat
		cd $WORKING_DIR
		mkdir unicornhat
		cp -R $TMPDIR/unicornhat/python/examples/* $WORKING_DIR/unicornhat/
		rm -rf $TMPDIR
		echo ""
		success "Examples copied to $WORKING_DIR/unicornhat/"
	else
		if confirm "Examples already exist, shall I replace them?"; then
			mv $WORKING_DIR/unicornhat $WORKING_DIR/unicornhat-backup
			echo "Updating Unicorn Hat examples..."
			export TMPDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
			cd $TMPDIR
			git clone https://github.com/pimoroni/unicornhat
			cd $WORKING_DIR
			mkdir unicornhat
			cp -R $TMPDIR/unicornhat/python/examples/* $WORKING_DIR/unicornhat/
			rm -rf $TMPDIR
			echo ""
			warning "I backed up the examples to unicornhat-backup, just in case you've changed anything!"
			success "Examples copied to $WORKING_DIR/unicornhat/"
		fi
	fi

	echo ""
	success "All done!"
	echo ""
	echo "For examples"
	echo "see https://github.com/pimoroni/UnicornHat/tree/master/python/examples"
	echo "And visit forums.pimoroni.com for support"
	echo "Have fun!"
	echo ""
else
	echo ""
	echo "Aborting..."
	echo ""
fi
