#!/bin/bash

echo ""
echo "This script will install Unicorn Hat libraries"
echo "and dependencies for both Python 2 and 3."
echo ""
echo "This process may take several minutes."
echo ""
echo "--- Warning ---"
echo ""
echo "Always be careful when running scripts and commands"
echo "copied from the internet. Ensure they are from a"
echo "trusted source."
echo ""
echo "If you want to see what this script does before"
echo "running it, you should run:"
echo "    \curl -sS get.pimoroni.com/unicornhat"
echo ""
echo ""


read -r -p "Do you wish to continue? [y/N] " response < /dev/tty
response=${response,,}

if [[ $response =~ ^(yes|y)$ ]]
then
	echo ""
	echo "Updating package indexes..."
	sudo apt-get update
	
	echo ""
	echo "Installing UnicornHat requirements..."

	\curl -sS get.pimoroni.com/package | bash -s - "python-pip"
	\curl -sS get.pimoroni.com/package | bash -s - "python-dev"
	\curl -sS get.pimoroni.com/package | bash -s - "python3-pip"
	\curl -sS get.pimoroni.com/package | bash -s - "python3-dev"
	
	echo ""
	echo "Installing UnicornHat for Python 2..."
	sudo pip install unicornhat

	echo ""
	echo "Installing UnicornHat for Python 3..."
	sudo pip-3.2 install unicornhat

	echo ""
	echo "Unicorn Paint requires the Flask python module ( Python 2.x only )"
	read -r -p "Would you like to install it? [Y/n]" response < /dev/tty
	response=${response,,}

	if [[ $response =~ ^(yes|y)$ ]]
	then
		echo ""
		sudo pip install flask
		echo ""
	fi

	read -r -p "Would you like to download Unicorn Hat example code? [Y/n] " response < /dev/tty
	response=${response,,}

	if [[ $response =~ ^(yes|y)$ ]]
	then

		echo ""
		echo "Downloading to $(pwd)/unicornhat"
		echo ""
		git clone https://github.com/pimoroni/unicornhat

		echo ""
		echo "All done!"
		echo "For examples"
		echo "see $(pwd)/unicornhat/python/examples"
		echo "Have fun!"
		echo ""

	else
	
		echo ""
		echo "All done!"
		echo "For examples"
		echo "see https://github.com/pimoroni/UnicornHat/tree/master/python/examples"
		echo "And visit forums.pimoroni.com for support"	
		echo "Have fun!"
		echo ""

	fi


else
	echo ""
	echo "Aborting..."
	echo ""
fi
