#!/bin/bash

git diff --no-prefix installers/template > update.patch

for FILE in installers/*; do

    REJECT="${FILE/installers/rejected}.rej"
    printf "Patching $FILE - rejections to $REJECT\n"
    patch --reject-file=$REJECT --input update.patch $FILE

done

rm update.patch
