#!/bin/bash

: <<'DISCLAIMER'

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

This script is licensed under the terms of the MIT license.
Unless otherwise noted, code reproduced herein
was written for this script.

- The Pimoroni Crew -

DISCLAIMER

productname="na" # the name of the product to install
scriptname="audio" # the name of this script
debugmode="no" # whether the script should use debug routines
debuguser="none" # optional test git user to use in debug mode
debugpoint="none" # optional git repo branch or tag to checkout
forcesudo="no" # whether the script requires to be ran with root privileges
promptreboot="no" # whether the script should always prompt user to reboot
customcmd="yes" # whether to execute commands specified before exit
raspbianonly="no" # whether the script is allowed to run on other OSes
macosxsupport="no" # whether Mac OS X is supported by the script
osreleases=( "Raspbian" "Ubuntu" "Debian" ) # list all the os-releases supported

FORCE=$1
DEVICE_TREE=true
ASK_TO_REBOOT=false
CURRENT_SETTING=false
UPDATE_DB=false

BOOTCMD=/boot/cmdline.txt
CONFIG=/boot/config.txt
APTSRC=/etc/apt/sources.list
INITABCONF=/etc/inittab
BLACKLIST=/etc/modprobe.d/raspi-blacklist.conf
LOADMOD=/etc/modules
DTBODIR=/boot/overlays

confirm() {
    if [ "$FORCE" == '-y' ]; then
        true
    else
        read -r -p "$1 [y/N] " response < /dev/tty
        if [[ $response =~ ^(yes|y|Y)$ ]]; then
            true
        else
            false
        fi
    fi
}

prompt() {
        read -r -p "$1 [y/N] " response < /dev/tty
        if [[ $response =~ ^(yes|y|Y)$ ]]; then
            true
        else
            false
        fi
}

success() {
    echo "$(tput setaf 2)$1$(tput sgr0)"
}

warning() {
    echo "$(tput setaf 1)$1$(tput sgr0)"
}

newline() {
    echo ""
}

sudocheck() {
    if [ $(id -u) -ne 0 ]; then
        echo -e "Install must be run as root. Try 'sudo ./$scriptname'\n"
        exit 1
    fi
}

sysclean() {
    sudo apt-get clean && sudo apt-get autoclean
    sudo apt-get -y autoremove &> /dev/null
}

sysupdate() {
    if ! $UPDATE_DB; then
        sudo apt-get update
        UPDATE_DB=true
    fi
}

sysupgrade() {
    sudo apt-get update && sudo apt-get upgrade
    sudo apt-get clean && sudo apt-get autoclean
    sudo apt-get -y autoremove &> /dev/null
}

sysreboot() {
    warning "Some changes made to your system require"
    warning "your computer to reboot to take effect."
    newline
    if prompt "Would you like to reboot now?"; then
        sync && sudo reboot
    fi
}

arch_check() {
    IS_ARMHF=false
    IS_ARMv6=false

    if uname -m | grep "armv.l" > /dev/null; then
        IS_ARMHF=true
        if uname -m | grep "armv6l" > /dev/null; then
            IS_ARMv6=true
        fi
    fi
}

os_check() {
    IS_RASPBIAN=false
    IS_MACOSX=false
    IS_SUPPORTED=false

    if [ -f /etc/os-release ]; then
        if cat /etc/os-release | grep "Raspbian" > /dev/null; then
            IS_RASPBIAN=true && IS_SUPPORTED=true
        fi
        if command -v apt-get &> /dev/null; then
            for os in ${osreleases[@]}; do
                if cat /etc/os-release | grep "$os" > /dev/null; then
                    IS_SUPPORTED=true
                fi
            done
        fi
    elif uname -s | grep "Darwin" > /dev/null; then
        IS_MACOSX=true
        if [ $macosxsupport == "yes" ]; then
            IS_SUPPORTED=true
        fi
    fi
}

raspbian_check() {
    IS_SQUEEZE=false
    IS_WHEEZY=false
    IS_JESSIE=false

    if [ -f /etc/os-release ]; then
        if cat /etc/os-release | grep "jessie" > /dev/null; then
            IS_JESSIE=true
        elif cat /etc/os-release | grep "wheezy" > /dev/null; then
            IS_WHEEZY=true
        elif cat /etc/os-release | grep "squeeze" > /dev/null; then
            IS_SQUEEZE=true
        else
            echo "Unsupported distribution"
            exit 1
        fi
    fi
}

raspbian_old() {
    if $IS_SQUEEZE || $IS_WHEEZY ;then
        true
    else
        false
    fi
}

force_hdmi() {
    if [ -e $CONFIG ] && ! grep -q "^hdmi_force_hotplug=1$" $CONFIG; then
        if grep -q "^#hdmi_force_hotplug=1$" $CONFIG; then
            sudo sed -i "s|^#hdmi_force_hotplug=1|hdmi_force_hotplug=1|" $CONFIG &> /dev/null
        else    
            echo "hdmi_force_hotplug=1" | sudo tee -a $CONFIG &> /dev/null
        fi
        ASK_TO_REBOOT=true
    fi
}

hotplug_hdmi() {
    if [ -e $CONFIG ] && grep -q "^hdmi_force_hotplug=1$" $CONFIG; then
        sudo sed -i "s|^hdmi_force_hotplug=1|#hdmi_force_hotplug=1|" $CONFIG &> /dev/null
        ASK_TO_REBOOT=true
    fi
}

route_audio() {
    if [ $debugmode == "yes" ]; then
        warning "passed parameter is $FORCE"
    fi
    if [ "$FORCE" == '1' ]; then
        amixer cset numid=3 1 > /dev/null
        success "Audio output mode changed to Analog!"
        hotplug_hdmi
    elif [ "$FORCE" == '2' ]; then
        amixer cset numid=3 2 > /dev/null
        success "Audio output mode changed to HDMI!"
        hotplug_hdmi
    elif [ "$FORCE" == '3' ]; then
        amixer cset numid=3 2 > /dev/null
        success "Audio signal will be forcefully sent to HDMI!"
        force_hdmi
    else
        newline
        echo "Please choose an audio output mode:" && newline
        echo "0 : Automatic signal detection"
        echo "1 : Output to analogue (headphone/speaker jack)"
        echo "2 : Output to digital (HDMI port)"
        echo "3 : Force route to digital (HDMI hotplug disabled)"
        newline        
        read -r -p "Enter an option [0-3]:" choice < /dev/tty
        if [ $debugmode == "yes" ]; then
            echo "User chose option $choice"
        fi
        if [[ $choice =~ ^(0|1|2)$ ]]; then
            amixer cset numid=3 $choice  > /dev/null
            success "Audio output mode changed!"
            hotplug_hdmi
            test_audio
        elif [[ $choice =~ ^(3)$ ]]; then
            amixer cset numid=3 $choice  > /dev/null
            success "Audio signal will be forcefully sent to HDMI!"
            force_hdmi
            test_audio
        else
            warning "Invalid option!"
            route_audio
        fi
    fi
}

test_audio() {
    newline
    if confirm "Do you wish to test your system now?"; then
        newline && echo "Testing..."
        speaker-test -l5 -c2 -t wav
    fi
}

: <<'MAINSTART'

Perform all global variables declarations as well as function definition
above this section for clarity, thanks!

MAINSTART

arch_check
os_check

if ! $IS_ARMHF; then
    warning "This hardware is not supported, sorry!"
    newline && exit 1
fi

if ! $IS_RASPBIAN && [ $raspbianonly == "yes" ]; then
    warning "Your operating system is not supported, sorry!"
    newline && exit 1
elif ! $IS_SUPPORTED; then
    warning "Your operating system is not supported, sorry!"
    newline && exit 1
fi

if [ $forcesudo == "yes" ]; then
    sudocheck
fi

newline
echo "This script will configure your Pi audio output!"
newline
warning "--- Warning ---"
newline
echo "Always be careful when running scripts and commands"
echo "copied from the internet. Ensure they are from a"
echo "trusted source."
newline
echo "If you want to see what this script does before"
echo "running it, you should run:"
echo "    \curl -sS https://get.pimoroni.com/$scriptname"
newline

if confirm "Do you wish to continue?"; then

    if [ -e $CONFIG ] && grep -q -E "^dtparam=audio=on$" $CONFIG; then
        bcm2835off="no"
    elif [ -e $LOADMOD ] && grep -q "^snd-bcm2835" $LOADMOD; then
        bcm2835off="no"
    else
        bcm2835off="yes"
    fi

    if [ $bcm2835off == "no" ]; then
        newline
        route_audio
        newline
    else
        newline
        warning "Default sound driver currently not loaded"
        warning "This script must now exit." && exit 1
    fi

    if [ $promptreboot == "yes" ] || $ASK_TO_REBOOT; then
        sysreboot && newline
    fi
else
    newline && echo "Aborting..." && newline
fi

exit 0
