#!/bin/bash

: <<'DISCLAIMER'

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

This script is licensed under the terms of the MIT license.
Unless otherwise noted, code reproduced herein
was written for this script.

- The Pimoroni Crew -

DISCLAIMER

productname="ESP IoT pHAT" # the name of the product to install
scriptname="iotphat" # the name of this script
debugmode="no" # whether the script should use test Git user, branch and routines
forcesudo="no" # whether the script requires to be ran with root privileges
promptreboot="no" # whether the script should always prompt user to reboot
customcmd="no" # whether to execute commands specified before exit
i2creq="no" # whether i2c interface is required or not
spireq="no" # whether spi interface is required or not
uartreq="yes" # whether uart communication is required or not
armv6="yes" # whether armv6 processors is supported or not
armv7="yes" # whether armv7 processors is supported or not
armv8="yes" # whether armv8 processors is supported or not
raspbianonly="yes" # whether the script is allowed to run on other OSes
squeezesupport="no" # whether Squeeze is supported or not
wheezysupport="yes" # whether Wheezy is supported or not
jessiesupport="yes" # whether Jessie is supported or not
debpackage="na" # the name of the package in apt repo
piplibname="na" # the name of the lib in pip repo
pipoverride="yes" # whether the script should give priority to pip repo
pip2support="yes" # whether python2 is supported or not
pip3support="no" # whether python3 is supported or not
localdir="espiotphat" # the name of the dir for copy of examples
gitreponame="espiot-phat" # the name of the git project repo
gitusername="pimoroni" # the name of the git user to fetch repo from
gitrepobranch="master" # repo branch to checkout
gitrepoclone="no" # whether the git repo is to be cloned locally
gitclonedir="source" # the name of the local dir for repo
repoclean="no"  # whether any git repo clone found should be cleaned up
repoinstall="no" # whether the library should be installed from repo
libdir="na" # subdirectory of library in repo
copydir=( "firmware" ) # subdirectories to copy from repo
pipdeplist=( "pyserial" "esptool" ) # list of dependencies to source from pip
pkgaptremove=( "python-serial" ) # list of conflicting apt packages to remove
pkgdeplist7=( "git" "python-pip" "python-rpi.gpio" ) # list core dependencies
pkgdeplist8=( "python-gpiozero" ) # list extra dependencies assuming Jessie
moreaptdep=( "minicom" ) # list of all the additional apt dependencies
morepipdep=() # list of all the additional pip dependencies
spacereq=150 # minimum size required on root partition in MB

#based on template 1607111345

FORCE=$1
DEVICE_TREE=true
ASK_TO_REBOOT=false
CURRENT_SETTING=false
INTERACTIVE=false
UPDATE_DB=false
REMOVE_PKG=false

BOOTCMD=/boot/cmdline.txt
CONFIG=/boot/config.txt
APTSRC=/etc/apt/sources.list
INITABCONF=/etc/inittab
BLACKLIST=/etc/modprobe.d/raspi-blacklist.conf
LOADMOD=/etc/modules

RASPOOL="http://archive.raspbian.org/raspbian/pool"
DEBPOOL="http://ftp.uk.debian.org/debian/pool"

confirm() {
    if [ "$FORCE" == '-y' ]; then
        true
    else
        read -r -p "$1 [y/N] " response < /dev/tty
        if [[ $response =~ ^(yes|y|Y)$ ]]; then
            true
        else
            false
        fi
    fi
}

success() {
    echo "$(tput setaf 2)$1$(tput sgr0)"
}

warning() {
    echo "$(tput setaf 1)$1$(tput sgr0)"
}

newline() {
    echo ""
}

sudocheck() {
    if [ $(id -u) -ne 0 ]; then
        echo -e "Install must be run as root. Try 'sudo ./$scriptname'\n"
        exit 1
    fi
}

sysclean() {
    sudo apt-get clean && sudo apt-get autoclean
    sudo apt-get -y autoremove &> /dev/null
}

sysupdate() {
    sudo apt-get update
}

sysupdgrade() {
    sudo apt-get update && sudo apt-get upgrade
    sudo apt-get clean && sudo apt-get autoclean
    sudo apt-get -y autoremove &> /dev/null
}

sysreboot() {
    warning "Some changes made to your system require"
    warning "your computer to reboot to take effect."
    newline
    if confirm "Would you like to reboot now?"; then
        sync
        sudo reboot
    fi
}

arch_check() {
    IS_ARMv6=false

    if uname -m | grep "armv6l" > /dev/null; then
        IS_ARMv6=true
    fi
}

os_check() {
    IS_RASPBIAN=false
    IS_MACOSX=false
    IS_X86_64=false
    IS_X86_32=false

    if [ -f /etc/os-release ] && cat /etc/os-release | grep "Raspbian" > /dev/null; then
        IS_RASPBIAN=true
    elif uname -s | grep "Darwin" > /dev/null; then
        IS_MACOSX=true
    elif uname -m | grep "x86_64" > /dev/null; then
        IS_X86_64=true
    else
        IS_X86_32=true
    fi
}

raspbian_check() {
    IS_SQUEEZE=false
    IS_WHEEZY=false
    IS_JESSIE=false

    if [ -f /etc/os-release ]; then
        if cat /etc/os-release | grep "jessie" > /dev/null; then
            IS_JESSIE=true
        elif cat /etc/os-release | grep "wheezy" > /dev/null; then
            IS_WHEEZY=true
        elif cat /etc/os-release | grep "squeeze" > /dev/null; then
            IS_SQUEEZE=true
        else
            echo "Unsupported distribution"
            exit 1
        fi
    fi
}

raspbian_old() {
    if $IS_SQUEEZE || $IS_WHEEZY ;then
        true
    else
        false
    fi
}

servd_trig() {
    if command -v service > /dev/null; then
        sudo service $1 $2
    fi
}

get_init_sys() {
    if command -v systemctl > /dev/null && systemctl | grep -q '\-\.mount'; then
        SYSTEMD=1
    elif [ -f /etc/init.d/cron ] && [ ! -h /etc/init.d/cron ]; then
        SYSTEMD=0
    else
        echo "Unrecognised init system" && exit 1
    fi
}

usb_max_power() {
    if $IS_RASPBIAN; then
        if [ -e $CONFIG ] && grep -q "^max_usb_current=1$" $CONFIG; then
            newline
            echo "Max USB current setting already active"
        else
            newline
            echo "Adjusting USB current setting in $CONFIG"
            echo "max_usb_current=1" | sudo tee -a $CONFIG
            newline
            ASK_TO_REBOOT=true
        fi
    fi
}

force_hdmi() {
    if $IS_RASPBIAN; then
        if [ -e $CONFIG ] && grep -q "^hdmi_force_hotplug=1$" $CONFIG; then
            \curl -sS get.pimoroni.com/audio | sudo bash -s - "2"
        else
            echo "hdmi_force_hotplug=1" | sudo tee -a $CONFIG &> /dev/null
            \curl -sS get.pimoroni.com/audio | sudo bash -s - "2"
            ASK_TO_REBOOT=true
        fi
    fi
}

space_chk() {
    if command -v stat > /dev/null && ! $IS_MACOSX; then
        if [ $spacereq -gt $(($(stat -f -c "%a*%S" /)/10**6)) ];then
            newline
            warning  "There is not enough space left to proceed with  installation"
            if confirm "Would you like to attempt to expand your filesystem?"; then
                \curl -sS get.pimoroni.com/expandfs | sudo bash
                exit 1
            else
                newline
                exit 1
            fi
        fi
    fi
}

apt_pkg_req() {
    APT_CHK=$(dpkg-query -W -f='${Status}\n' $1 2> /dev/null | grep "install ok installed")

    if [ "" == "$APT_CHK" ]; then
        true
    else
        false
    fi
}

apt_pkg_install() {
    \curl -sS get.pimoroni.com/package | sudo bash -s - $1 || { warning "Sorry, Apt failed to install $1, I can't continue!" && exit 1; }
}

pip_pkg_req() {
    PIP_CHK=$(pip search $1 | grep INSTALLED)

    if [ "" == "$PIP_CHK" ]; then
        true
    else
        false
    fi
}

pip_chk_pip3() {
    if command -v pip3 > /dev/null; then
        PIP3_BIN="pip3"
    elif command -v pip-3.2 > /dev/null; then
        PIP3_BIN="pip-3.2"
    else
        PIP3_BIN=""
    fi
}

pip_pkg_req3() {
    PIP_CHK=$($PIP3_BIN search $1 | grep INSTALLED)

    if [ "" == "$PIP_CHK" ]; then
        true
    else
        false
    fi
}

: <<'MAINSTART'

Perform all global variables declarations as well as function definition
above this section for clarity, thanks!

MAINSTART

if [ "$FORCE" != '-y' ]; then
    space_chk
fi

arch_check
os_check

if $IS_RASPBIAN; then
    raspbian_check
    if [ $squeezesupport == "no" ] && $IS_SQUEEZE; then
        newline
        warning "--- Warning ---"
        newline
        echo "The $productname installer"
        echo "does not work on this version of Raspbian."
        echo "Check https://github.com/$gitusername/$gitreponame"
        echo "for additional information and support"
        newline
        exit 1
    fi
    if [ $wheezysupport == "no" ] && $IS_WHEEZY; then
        newline
        warning "--- Warning ---"
        newline
        echo "The $productname installer"
        echo "does not work on this version of Raspbian."
        echo "Check https://github.com/$gitusername/$gitreponame"
        echo "for additional information and support"
        newline
        exit 1
    fi
elif ! $IS_RASPBIAN && [ $raspbianonly == "yes" ]; then
    warning "Warning!"
    echo "Please only run this script on Raspbian on your Raspberry Pi"
    exit 1
else
    if [ $debugmode != "no" ]; then
        newline
        echo "IS_RASPBIAN is $IS_RASPBIAN"
        echo "IS_MACOSX is $IS_MACOSX"
        echo "IS_X86_64 is $IS_X86_64"
        echo "IS_X86_32 is $IS_X86_32"
    fi
fi

if [ $forcesudo == "yes" ]; then
    sudocheck
fi

if [ $pipoverride == "yes" ]; then    
    debpackage="na"
else
    piplibname="na"    
fi

if [ $debugmode != "no" ]; then    
    gitusername="$debugmode"
    gitrepobranch="testing"
    newline
    warning "debug mode: $gitusername user and $gitrepobranch branch"
fi

newline
echo "This script will install everything needed to use"
echo "$productname"
newline
warning "--- Warning ---"
newline
echo "Always be careful when running scripts and commands"
echo "copied from the internet. Ensure they are from a"
echo "trusted source."
newline
echo "If you want to see what this script does before"
echo "running it, you should run:"
echo "    \curl -sS get.pimoroni.com/$scriptname"
newline

if [ $i2creq == "yes" ]; then
    echo "Note: $productname requires I2C communication"
fi
if [ $spireq == "yes" ]; then
    echo "Note: $productname requires SPI communication"
fi
if [ $uartreq == "yes" ]; then
    echo "Note: $productname requires UART communication"
    warning "The serial console will be enabled if you proceed!"
fi

newline

if confirm "Do you wish to continue?"; then

    newline
    echo "Checking hardware requirements..."

    if [ $uartreq == "yes" ]; then
        newline
        echo "UART must be Enabled for $productname to work"
        \curl -sS get.pimoroni.com/uarton | sudo bash -s - "-y"
        ASK_TO_REBOOT=true
        newline
    fi

    if [ $spireq == "yes" ]; then
        newline
        if ls /dev/spi* &> /dev/null; then
            success "SPI Already Enabled"
        else
            echo "SPI must be Enabled for $productname to work"
            \curl -sS get.pimoroni.com/spi | sudo bash -s - "-y"
            ASK_TO_REBOOT=true
        fi
    fi

    if [ $i2creq == "yes" ]; then
        newline
        if ls /dev/i2c* &> /dev/null; then
            success "I2C Already Enabled"
        else
            echo "I2C must be Enabled for $productname to work"
            \curl -sS get.pimoroni.com/i2c | sudo bash -s - "-y"
            ASK_TO_REBOOT=true
        fi
    fi
    success "Done!"
    newline

    echo "Checking install requirements..."

    if command -v apt-get > /dev/null; then

        for pkgrm in ${pkgaptremove[@]}; do
            if apt_pkg_req "$pkgrm"; then
                REMOVE_PKG=true
            fi
        done
        if [ $debpackage != "na" ]; then
            UPDATE_DB=true
        fi
        for pkgdep in ${pkgdeplist7[@]}; do
            if apt_pkg_req "$pkgdep"; then
                UPDATE_DB=true
            fi
        done
        for pkgdep in ${pkgdeplist8[@]}; do
            if apt_pkg_req "$pkgdep"; then
                UPDATE_DB=true
            fi
        done
        for morepkgdep in ${moreaptdep[@]}; do
            if apt_pkg_req "$morepkgdep"; then
                UPDATE_DB=true
            fi
        done

        if $UPDATE_DB; then
            newline
            echo "Updating package indexes..."
            sysupdate
            newline
            echo "Checking for dependencies..."

            if $REMOVE_PKG; then
                for pkgrm in ${pkgaptremove[@]}; do
                    warning "Installed package conflicts with requirements"
                    sudo apt-get remove "$pkgrm"
                done
            fi
            for pkgdep in ${pkgdeplist7[@]}; do
                if apt_pkg_req "$pkgdep"; then
                    apt_pkg_install "$pkgdep"
                fi
            done
            if ! raspbian_old; then
                for pkgdep in ${pkgdeplist8[@]}; do
                    if apt_pkg_req "$pkgdep"; then
                        apt_pkg_install "$pkgdep"
                    fi
                done
            fi
            if [ $debpackage != "na" ]; then
                apt_pkg_install "$debpackage"
            fi
        else
            success "Done!"
        fi
    fi

    pip_chk_pip3

    for pipdep in ${pipdeplist[@]}
        do if pip_pkg_req "$pipdep"; then
            if [ $pip2support == "yes" ] && command -v python > /dev/null; then
            sudo pip install "$pipdep"
            fi
            if [ $pip3support == "yes" ] && command -v python3 > /dev/null; then
        sudo $PIP3_BIN install "$pipdep"
            fi
        fi
    done

    if [ $piplibname != "na" ] && [ $debpackage == "na" ]; then
        if [ $pip2support == "yes" ] && [ -n $(which python2) ]; then
            if command -v pip > /dev/null; then
                newline
                echo "Checking for Python 2 library..."

                if pip_pkg_req "$piplibname"; then
                    echo "Installing $productname library for Python 2..."
                    newline
                    if ! sudo pip install $piplibname; then
                        warning "Python 2 library install failed!"
                        echo "If problems persist, visit forums.pimoroni.com for support"
                        exit 1
                    fi
                    success "Done!"
                else
                    success "Found!"
                    newline
                    if confirm "Python 2 module found. Reinstall/Update?"; then
                        if ! sudo pip install $piplibname -I; then
                            warning "Python 2 library install failed!"
                            echo "If problems persist, visit forums.pimoroni.com for support"
                            exit 1
                        fi
                        success "Done!"
                    fi
                fi
            fi
        else
            echo "Note: $productname currently supports Python 3 only."
        fi

        if [ $pip3support == "yes" ] && [ -n $(which python3) ]; then
            if [ -n "$PIP3_BIN" ]; then
                newline
                echo "Checking for Python 3 library..."
                if pip_pkg_req3 "$piplibname"; then
                    echo "Installing $productname library for Python 3..."
                    newline
                    if ! sudo $PIP3_BIN install $piplibname; then
                        warning "Python 3 library install failed!"
                        echo "If problems persist, visit forums.pimoroni.com for support"
                        exit 1
                    fi
                else
                    success "Found!"
                    newline
                    if confirm "Python 3 module found. Reinstall/Update?"; then
                        if ! sudo $PIP3_BIN install $piplibname -I; then
                            warning "Python 3 library install failed!"
                            echo "If problems persist, visit forums.pimoroni.com for support"
                            exit 1
                        fi
                        success "Done!"
                    fi
                fi
            fi
        else
            if [ $pip3support == "no" ]; then
                echo "Note: $productname currently supports Python 2 only."
            else
                echo "Python3-pip does not seem to be installed"
            fi
        fi
    fi

    if ! $IS_MACOSX; then
        if [ $EUID -ne 0 ]; then
            USER_HOME=$(getent passwd $USER | cut -d: -f6)
        else
            if $SUDO_USER; then
                USER_HOME=$(getent passwd $SUDO_USER | cut -d: -f6)
            else
                warning "Running as root and no other sudo user available"
                exit 1
            fi
        fi
    else
        if [ $EUID -ne 0 ]; then
            USER_HOME=$(dscl . -read /Users/$USER NFSHomeDirectory | cut -d: -f2)
        else
            USER_HOME=$(dscl . -read /Users/$SUDO_USER NFSHomeDirectory | cut -d: -f2)
        fi
    fi

    WORKING_DIR="$USER_HOME/Pimoroni"

    if ! [ -d $WORKING_DIR ]; then
            mkdir $WORKING_DIR
    fi

    if [ -n "$copydir" ]; then
        echo "Downloading examples and documentation..."
        if ! [ -d $WORKING_DIR/$localdir ]; then
            newline
            TMPDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
            cd $TMPDIR
            git clone --depth=1 https://github.com/$gitusername/$gitreponame
            cd $WORKING_DIR
            mkdir $localdir
            for repodir in ${copydir[@]}; do
                cp -R $TMPDIR/$gitreponame/$repodir $WORKING_DIR/$localdir/$repodir
            done
            rm -rf $TMPDIR
            success "Resources copied to $WORKING_DIR/$localdir/"
        else
            newline
            if confirm "Resources already exist, shall I replace them?"; then
                mv $WORKING_DIR/$localdir $WORKING_DIR/$localdir-backup
                TMPDIR=`mktemp -d /tmp/pimoroni.XXXXXX`
                cd $TMPDIR
                git clone --depth=1 https://github.com/$gitusername/$gitreponame
                cd $WORKING_DIR
                mkdir $localdir
                for repodir in ${copydir[@]}; do
                    cp -R $TMPDIR/$gitreponame/$repodir $WORKING_DIR/$localdir/$repodir
                done
                rm -rf $TMPDIR
                warning "I backed up the examples to $localdir-backup, just in case you've changed anything!"
                success "Resources copied to $WORKING_DIR/$localdir/"
            fi
        fi
    fi

    newline
    echo "Checking for additional software..."

    moredepreq=false

    for moredep in ${moreaptdep[@]}
        do if apt_pkg_req "$moredep"; then
            moredepreq=true
        fi
        done
    for moredep in ${morepipdep[@]}
        do if pip_pkg_req "$moredep"; then
            moredepreq=true
        fi
        done

    if $moredepreq; then
        newline
        echo "Some $productname examples/plugins"
        echo "require additional software and/or modules"
        if confirm "Would you like to install them now?"; then
            for moredep in ${moreaptdep[@]}
                do if apt_pkg_req "$moredep"; then
                    apt_pkg_install "$moredep"
                fi
                done
            for moredep in ${morepipdep[@]}
                do if pip_pkg_req "$moredep"; then
                    sudo pip install "$moredep"
                    sudo $PIP3_BIN install "$moredep"
                fi
                done
        fi
    else
        success "Done!"
    fi

    if [ $gitrepoclone == "yes" ]; then
        if ! [ -d $WORKING_DIR/$localdir ]; then
            mkdir $WORKING_DIR/$localdir
        fi
        if [ $gitclonedir == "source" ]; then
            gitclonedir=$gitreponame
        fi
        if [ $repoclean == "yes" ]; then
            rm -Rf $WORKING_DIR/$localdir/$gitclonedir
        fi
        if [ -d $WORKING_DIR/$localdir/$gitclonedir ]; then
            newline
            echo "Github repo already present. Updating..."
            cd $WORKING_DIR/$localdir/$gitclonedir
            git pull
        else
            newline
            echo "Cloning Github repo locally..."
            cd $WORKING_DIR/$localdir
            if [ $gitrepobranch != "master" ]; then
                git clone https://github.com/$gitusername/$gitreponame $gitclonedir -b $gitrepobranch
            else
                git clone --depth=1 https://github.com/$gitusername/$gitreponame $gitclonedir
            fi
        fi
    fi

    if [ $repoinstall == "yes" ]; then
        newline
        echo "Installing library..."
        newline
        cd $WORKING_DIR/$localdir/$gitreponame/$libdir
        if [ $pip2support == "yes" ] && command -v python > /dev/null; then
            sudo python ./setup.py install
        fi
        if [ $pip3support == "yes" ] && command -v python3 > /dev/null; then
            sudo python3 ./setup.py install
        fi
        newline
        success "Done!"
    fi

    if [ $customcmd == "no" ]; then
        newline
        echo "Finalising Install..."
        newline
        sysclean
        newline
        success "All done!"
        newline
        echo "Enjoy your $productname!"
        if [ $pip3support == "no" ]; then
            echo "Note: $productname currently supports Python 2 only."
        fi
        if [ $pip2support == "no" ]; then
            echo "Note: $productname currently supports Python 3 only."
        fi
        newline
    else # custom block starts here
        newline
        echo "Finalising Install..."
        # place all custom commands in this scope
        newline
    fi

    if [ $promptreboot == "yes" ] || $ASK_TO_REBOOT; then
        sysreboot
        newline
    fi
else
    newline
    echo "Aborting..."
    newline
fi

exit 0
