#!/bin/bash

success () {
    echo "$(tput setaf 2)$1$(tput sgr0)"
}

PKG_OK=$(dpkg-query -W -f='${Status}\n' $1 2> /dev/null | grep "install ok installed")

echo "Checking for $1..."

if [ "" == "$PKG_OK" ]; then
    echo "$1 required. Installing."
    echo "Running sudo apt-get install $1"
    echo ""
    sudo apt-get --force-yes --yes install $1
    STATUS=$?
    echo ""
else
    success "$1 already installed."
    STATUS=0
fi

exit $STATUS
